spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5431/product_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate  # flyway akan handle DDL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        web: DEBUG